### ISSUE TITLE
Create API to sit between BackStage -> TimeSeries DB

### ISSUE THREAD

**Issue by Wolftousen** [liatrio/liatrio-dora-api#1]
For now, we just need a skeleton API with a few endpoints for getting the different sets of DORA metrics, they can just return dummy data for now.

Adriel recommended we do this in GO due to GO having OTEL libraries that connect to time series databases easily.  I'm partial to Rust, but I'm not going to force anything, I don't know GO so wont be of much help here, at least not initially.

```[tasklist]
### Tasks
- [x] Deployment Frequency Endpoint
- [x] Time to Recover Endpoint
- [x] Change Lead Time Endpoint
- [x] Change Failure Rate Endpoint
```
